banknifty:
  - from: 2016-04-29
    to: 2018-10-25
    size: 40

  - from: 2018-10-26
    to: 2020-05-03
    size: 20

  - from: 2020-05-04
    to: 2023-08-31
    size: 25

  - from: 2023-09-01
    to: 2024-11-25
    size: 15

  - from: 2024-11-26
    to: null
    size: 30


nifty:
  - from: 2015-08-20
    to: 2021-04-29
    size: 75

  - from: 2021-04-30
    to: 2024-04-25
    size: 50

  - from: 2024-04-26
    to: 2024-11-25
    size: 25

  - from: 2024-11-26
    to: 2025-12-30
    size: 75

  - from: 2025-12-31
    to: null
    size: 65


sensex:
  - from: 2024-12-27
    to: null
    size: 20


bankex:
  - from: 2024-12-27
    to: null
    size: 30


finnifty:
  - from: 2024-11-20
    to: 2025-01-30
    size: 25

  - from: 2025-01-31
    to: null
    size: 65
